### ISSUE TITLE
Problems spawning entities

### ISSUE THREAD

**Issue by MegaEskere** [fverne/cotz#77]
Hi, can u help me with the string to call anomalies and radiation entities with the comands /anomalyadd and /radiationadd?

Like this is the def of one anomaly :

PLUGIN.anomalydefs[1] = {
	name = "Burner",
	entityname = "anom_jarka",
	interval = 128,
	commonArtifacts = {
		"artifact_droplet",
		"artifact_bolt",
		"artifact_bonecluster"
	},
	rareArtifacts = {
		"artifact_crystal",
		"artifact_eye"
	},
	veryRareArtifacts = {
		"artifact_fireball",
	},
}

And here of one radiation zone:

LUGIN.radiationdefs[12] = {
	name = "Radiation Moderate Very Small",
	entityname = "rad_m_vs",
	interval = 99999,

u call the def of both with numbers but i cant spawn them. 

/anomalyadd 256 (radius) string¿?
/radiationadd string¿?¿

how i can call the def there?
thanks for the helps!

**Comment by fagnig** [comment]
These plugins were never meant for public consumption, and as such the arguments are quite unintuitive.
Both of the commands take a string consisting of 1's and 0's.
So /anomalyadd 256 10110 would allow for the first, third and fourth definition to spawn at that point.

Lets say you would like to have a radiation spawn point with just the radiation definition in the issue.
You would have to do the following command:
/radiationadd 000000000001
As the it is the 12th radiation definition.

I hope that makes sense.
