### ISSUE TITLE
Mistakes with weapons

### ISSUE THREAD

**Issue by Avunit-Fr** [fverne/cotz#87]
I'm currently having a little problem with the weapons

[ERROR] gamemodes/ix_cotz/schema/items/base/sh_newweapons.lua:48: attempt to call method 'GetWeaponDurability' (a nil value)
  1. PaintOver - gamemodes/ix_cotz/schema/items/base/sh_newweapons.lua:48
   2. unknown - gamemodes/ix_cotz/schema/derma/cl_inventory.lua:341
    3. PaintManual - [C]:-1
     4. PaintSubpanels - gamemodes/helix/gamemode/core/derma/cl_subpanel.lua:295
      5. unknown - gamemodes/ix_cotz/schema/derma/cl_menu.lua:458

**Comment by armdupe** [comment]
are you using the cw weapon base and the weapons both from this repository?

**Comment by armdupe** [comment]
closing as it has been 2 weeks without a response.

**Comment by avunit14** [comment]
> are you using the cw weapon base and the weapons both from this repository?

Yes
